name: test_py27
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - blas=1.0
  - bleach=3.3.0
  - ca-certificates=2021.10.8
  - certifi=2019.11.28
  - cffi=1.13.2
  - configparser=3.7.3
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - enum34=1.1.10
  - freetype=2.11.0
  - futures=3.3.0
  - intel-openmp=2021.4.0
  - ipaddress=1.0.23
  - ipykernel=4.10.0
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.3
  - jpeg=9d
  - jsonschema=2.6.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.3
  - jupyterlab=0.33.12
  - jupyterlab_launcher=0.11.2
  - libcxx=12.0.0
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.3
  - ninja=1.10.2
  - notebook=5.7.8
  - olefile=0.46
  - packaging=20.9
  - pandoc=2.16.1
  - pandocfilters=1.5.0
  - pathlib2=2.3.5
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - prometheus_client=0.9.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.7.0
  - pycparser=2.20
  - pygments=2.5.2
  - pyparsing=2.4.7
  - python=2.7.18
  - python_abi=2.7
  - pytorch=1.0.1
  - pyzmq=19.0.0
  - readline=8.1
  - scandir=1.10.0
  - send2trash=1.5.0
  - setuptools=44.0.0
  - simplegeneric=0.8.1
  - singledispatch=3.6.1
  - six=1.16.0
  - sqlite=3.36.0
  - subprocess32=3.5.4
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.11
  - torchvision=0.2.2
  - tornado=5.1.1
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.15.0
    - astor==0.8.1
    - backports-functools-lru-cache==1.6.4
    - backports-weakref==1.0.post1
    - boto3==1.17.112
    - botocore==1.20.112
    - bz2file==0.98
    - cachetools==3.1.1
    - chardet==4.0.0
    - funcsigs==1.0.2
    - functools32==3.2.3.post2
    - gast==0.2.2
    - gensim==3.8.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - grpcio==1.41.1
    - h5py==2.10.0
    - idna==2.10
    - jmespath==0.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.1.1
    - mock==3.0.5
    - numpy==1.16.1
    - oauthlib==3.1.0
    - opt-einsum==2.3.2
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-dateutil==2.8.2
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.5
    - s3transfer==0.4.2
    - scikit-learn==0.20.4
    - scipy==1.2.2
    - smart-open==1.10.1
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - urllib3==1.26.7
    - werkzeug==1.0.1
    - wrapt==1.13.3
